### PR TITLE
#1100 - Fix startup script for windows

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by nicolaferraro** [comment]
[merge]

**Comment by nicolaferraro** [comment]
Thanks @apupier!

**Comment by nicolaferraro** [comment]
[merge]

**Comment by nicolaferraro** [comment]
@hrishin any idea why CI is failing? It should be unrelated to this PR.

**Comment by apupier** [comment]
@hrishin any ideas?

**Comment by nicolaferraro** [comment]
retest this please

**Comment by nicolaferraro** [comment]
[merge]

**Pull request merged**
