### PR TITLE
Changed Ingress resource kind from BUILD to INGRESS. fabric8:resource (#1631)

### PR DESCRIPTION
**Pull request by nkkarthik**

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@nkkarthik :Thanks,  Could you also please add a line to changelog regarding this change?

**Comment by nkkarthik** [comment]
How do I add a changelog entry?

**Comment by rohanKanojia** [comment]
There is a file CHANGELOG.md in repository. You need to add a line regarding your change in 4.3-SNAPSHOT section

**Comment by nkkarthik** [comment]
Thank you, @rohanKanojia (I thought the file is autogenerated).  Added an entry to the changelog file.

**Pull request merged**
