### PR TITLE
Fix #1299 : autotls feature doesn't work with OpenShift 3.9 (Kubernetes 1.8+) due to InitContainer annotation deprecation

### LINKED ISSUE #1299: autotls feature doesn't work with OpenShift 3.9 (Kubernetes 1.8+) due to InitContainer annotation deprecation
The autotls feature uses initContainer alpha annotations (https://github.com/fabric8io/fabric8-maven-plugin/blob/bd414f1ad94fdf48e8de05f25e3e09998b3f7508/enricher/api/src/main/java/io/fabric8/maven/enricher/api/util/InitContainerHandler.java) but this has been deprecated as of Kubernetes 1.8.0 (https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#support-and-compatibility). 

We need to replace the annotation with the spec.initContainers field. 

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) : 3.3.9

* Kubernetes / OpenShift setup and version :
openshift v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657

* If it's a bug, how to reproduce :
Enable and use autotls feature. Initcontainer will not be created.

### PR DESCRIPTION
**Pull request by rohanKanojia**
#1299

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@nicolaferraro @hrishin : Could you please review? It's a super tiny PR ;)

**Comment by rhuss** [comment]
retest this

**Comment by rohanKanojia** [comment]
@rhuss : All checks have passed. Could you please take a look and approve so that we can proceed with merging?

**Comment by rhuss** [comment]
I think its ok when 1 reviewer (@nicolaferraro) approved it. So going to merge it now.

**Comment by rhuss** [comment]
Going to merge as the test fails because of the boosters (not part of this project) are failing. Hopefully we get #1317 fixed.

**Pull request merged**
