### PR TITLE
Get rid of (apparently) unused dependencies

### PR DESCRIPTION
**Pull request by rhuss**
especially the dependency on hibernate validator is annoying as hibernate validator tends to be a beast w.r.t to logging

### CODE REVIEW

**Comment by rhuss** [comment]
@nicolaferraro do you know whether we really need this (now removed) dependencies ? Its not actively used in the code, but maybe because of lookup of devtools.jar ? sorry not that deep in the code.

The problem is the hibernate-validator dep which is super noisy sometimes.

**Comment by nicolaferraro** [comment]
@rhuss let me do a check. Spring-boot sometimes refuses to start if you don't provide an implementation of JSR-303, but I don't see why it should stay in the plugin.

**Comment by nicolaferraro** [comment]
lgtm

The spring-boot remote watcher client definitely does not need `hibernate-validator` and libraries declared in the plugin are not included in the deployed artifact (exception made for `devtools.jar`). So they can be removed. We should also get rid of the `devtools` lib completely (#832).

**Comment by rhuss** [comment]
thanks for the cross check ! btw, agreed with everything you mention in #832

**Comment by rhuss** [comment]
[merge]

**Pull request merged**
