### PR TITLE
just use build.finalName for grabbing the swarm artifact; don't hardc…

### LINKED ISSUE #311: wildflyswarm generator doesn't find build.finalName artifact
currently hardcoded to ${project.artifactId}-${project.version}-swarm.jar.

should look at 

${project.build.directory}/${project.build.finalName}-swarm.jar

### PR DESCRIPTION
**Pull request by christian-posta**
…ode to {artifactId}-{version}-swarm.jar fixes #311

### CODE REVIEW

**Comment by jstrachan** [comment]
LGTM [merge]

**Comment by jstrachan** [comment]
@christian-posta looks like you maybe need to rebase am afraid

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
@christian-posta ah my bad - maybe not ;)

**Comment by rhuss** [comment]
I had this lately, too, that GitHub states that a branch is out of date for no obvious reason because I just did a rebase. Guess we could merge this PR manually here (would be the fastest)

**Comment by jstrachan** [comment]
@rhuss yeah, will do

**Pull request merged**
