### PR TITLE
adding a documentation about configuring <pluginGroups> in settings.xml so that fabric8 goals will be resolved

### PR DESCRIPTION
**Pull request by reynoldsm88**

### CODE REVIEW

**Comment by reynoldsm88** [comment]
This error does not seem related to my change...

`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project fabric8-maven-plugin-build: The preview mode, along with the 'sonar.analysis.mode' parameter, is no more supported. You should stop using this parameter. `

**Comment by rohanKanojia** [comment]
@reynoldsm88 :yeah, looks like we need to update this sonar check accordingly.

**Comment by reynoldsm88** [comment]
@rohanKanojia cool thanks. I was kind of mystified as to what was going on... I didn't think my change would have even been picked up by sonar :)

**Comment by reynoldsm88** [comment]
I was in a rush yesterday when I was setting something up. I fixed the grammar and provided more background as to why I believe this is necessary. I got stuck on this issue for a little bit and figured it would be helpful for other people.

**Comment by reynoldsm88** [comment]
Yea sure! I didn't realize I had comitted them :/. Sorry.

**Comment by dev-gaur** [comment]
@rohanKanojia 5 commits! Make sure you squash and merge before merging!

**Pull request merged**
