### PR TITLE
Fixed PortForwardServiceTest and Added ClusterAccessTest

### PR DESCRIPTION
**Pull request by piyush1594**
Fixed PortForwardServiceTest by changing the expectation in MockServer
Added test for ClusterAccess class
#1107

### CODE REVIEW

**Comment by rawlingsj** [comment]
ok to test

**Comment by rawlingsj** [comment]
add to whiltelist

**Comment by rawlingsj** [comment]
add to whitelist

**Comment by nicolaferraro** [comment]
Merged

**Comment by hrishin** [comment]
@nicolaferraro thank you Nicola

**Comment by piyush1594** [comment]
Thanks @nicolaferraro

**Pull request closed without merging**
