### PR TITLE
Pull request with fix for issue #6599: JavaExecGenerator in maven plugin 3.2: Problems with main class treatment in non-fat-jar deployments 

### PR DESCRIPTION
**Pull request by oweise**
I settled with removing the superfluous check of Config.mainClass, which is already done inside MainClassDetector, and let the getMainClass() call actually fill the var. This will let the JAVA_MAIN_CLASS_ENV_VAR be set for all non-fat-jar deployments and no longer be skipped.

Also the hasMainClass() method now should return true for any content of Config.mainClass.

Also a UnitTest was added to check for setting of the env var in three possible situations: 

- Configured main class in non-fat-jar
- Detected main class in non-fat-jar
- Fat-jar

### CODE REVIEW

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
@rhuss there is the PR.

lgtm

**Comment by davsclaus** [comment]
[merge]

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
[merge]

**Comment by davsclaus** [comment]
Its weird we get this error on merge but not on test
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Fabric8 Maven :: Generator :: Java Exec 3.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ fabric8-maven-generator-java-exec ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.0:resources (default-resources) @ fabric8-maven-generator-java-exec ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] ignoreDelta true
[INFO] Copying 2 resources
[INFO] Copying file META-INF/fabric8/generator-default
[INFO] Copying file assemblies/java-app.xml
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ fabric8-maven-generator-java-exec ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /mnt/hudson_workspace/workspace/fabric8-maven-plugin-pullreq-merge/generator/java-exec/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.0.0:testResources (default-testResources) @ fabric8-maven-generator-java-exec ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] ignoreDelta true
[INFO] Copying 1 resource
[INFO] Copying file fatjar-simple/test.jar
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ fabric8-maven-generator-java-exec ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /mnt/hudson_workspace/workspace/fabric8-maven-plugin-pullreq-merge/generator/java-exec/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ fabric8-maven-generator-java-exec ---
[INFO] Surefire report directory: /mnt/hudson_workspace/workspace/fabric8-maven-plugin-pullreq-merge/generator/java-exec/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.fabric8.maven.generator.javaexec.JavaExecGeneratorMainClassDeterminationTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.528 sec
Running io.fabric8.maven.generator.javaexec.JavaRunGeneratorTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.023 sec <<< FAILURE!
fromSelector(io.fabric8.maven.generator.javaexec.JavaRunGeneratorTest)  Time elapsed: 0.02 sec  <<< ERROR!
java.lang.IllegalStateException: JMockit wasn't properly initialized; please ensure that jmockit precedes junit in the runtime classpath, or use @RunWith(JMockit.class)
	at io.fabric8.maven.generator.javaexec.JavaRunGeneratorTest$1.<init>(JavaRunGeneratorTest.java:76)
	at io.fabric8.maven.generator.javaexec.JavaRunGeneratorTest.prepareExpectation(JavaRunGeneratorTest.java:76)
	at io.fabric8.maven.generator.javaexec.JavaRunGeneratorTest.fromSelector(JavaRunGeneratorTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running io.fabric8.maven.generator.javaexec.FatJarDetectorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
simple(io.fabric8.maven.generator.javaexec.FatJarDetectorTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:621)
	at org.junit.Assert.assertNotNull(Assert.java:631)
	at io.fabric8.maven.generator.javaexec.FatJarDetectorTest.simple(FatJarDetectorTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   simple(io.fabric8.maven.generator.javaexec.FatJarDetectorTest)

Tests in error: 
  fromSelector(io.fabric8.maven.generator.javaexec.JavaRunGeneratorTest): JMockit wasn't properly initialized; please ensure that jmockit precedes junit in the runtime classpath, or use @RunWith(JMockit.class)

Tests run: 5, Failures: 1, Errors: 1, Skipped: 0
```

@oweise do you have any test failure on your branch?

**Comment by oweise** [comment]
No sorry, works here.

Maybe I should just add the @RunWith(JMockit.class) to the new test as proposed by the message?

**Comment by davsclaus** [comment]
Yes try that

**Comment by oweise** [comment]
Done

**Comment by davsclaus** [comment]
[merge]

**Comment by davsclaus** [comment]
Yay that worked

**Pull request merged**
