### PR TITLE
OSFUSE-388: Remove OpenShift S2I buildconfig in undeploy goal, Replic…

### PR DESCRIPTION
**Pull request by dhirajsb**
…ationController is still not deleted even though OpenShift acks that delete

### CODE REVIEW

**Comment by dhirajsb** [comment]
OK to test

**Comment by dhirajsb** [comment]
@jimmidyson can you please kick this PR and merge if good?

**Comment by rhuss** [comment]
@dhirajsb will merge it (also to branch v3.1.80-redhat)

**Comment by rhuss** [comment]
[merge]

**Pull request merged**
