### PR TITLE
OSFUSE-452: Added support for specifying pod name for log goal

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
ok to test

**Comment by dhirajsb** [comment]
ok to test

**Comment by dhirajsb** [comment]
ok to merge

**Comment by dhirajsb** [comment]
[merge] lgtm

**Comment by dhirajsb** [comment]
@jimmidyson can you bless this PR?

**Comment by davsclaus** [comment]
[merge]

**Comment by davsclaus** [comment]
@dhirajsb do you mind doing a PR to update the fabric8:log documentation about this new option
https://maven.fabric8.io/#fabric8:log

**Comment by dhirajsb** [comment]
@davsclaus no problem, can you point me to the file to update? Or I can find it too.

**Comment by davsclaus** [comment]
Yeah the docs are in this git repo 
https://github.com/fabric8io/fabric8-maven-plugin/blob/master/doc/src/main/asciidoc/inc/goals/develop/_fabric8-log.adoc

Only for more overall docs they are in fabric8 git repo itself

**Comment by dhirajsb** [comment]
@davsclaus PRs sent

**Pull request merged**
