### PR TITLE
Provide better descriptions of the d-m-p mojo as they get displayed to a user in fabric8:help

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by chirino** [comment]
[lgtm] [merge]

**Comment by chirino** [comment]
[lgtm] [merge]

**Comment by rhuss** [comment]
lgtm [merge]

**Comment by rhuss** [comment]
[merge]

**Comment by rhuss** [comment]
why on earth does [merge] doesn't trigger a merge for me ? @fabric8io/maintainers any idea ?

**Comment by rhuss** [comment]
merged manually now ....

**Pull request merged**
