### PR TITLE
Allow to configure noCache option for openshift docker build strategy

### PR DESCRIPTION
**Pull request by bohmber**
See
https://docs.openshift.com/container-platform/3.6/dev_guide/builds/build_strategies.html#no-cache

Signed-off-by: bohmber <bommel@apache.org>

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@bohmber : Looks good, Thanks. Could you please add a line to CHANGELOG.md about this change?

**Comment by bohmber** [comment]
@rohanKanojia changelog added

**Comment by bohmber** [comment]
@dev-gaur you can do the squash during merge?

**Comment by lordofthejars** [comment]
@bohmber Yes I am going to squash at merge time, thank you very much.

**Pull request merged**
