### PR TITLE
Update FatJarDetector.java

### PR DESCRIPTION
**Pull request by eye0fra**
Making sure the jar archive is always close once the scan process has finished.
Otherwise the following issue happen (only in Windows environment):

` Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.33:build (default) on project app-sample: Execution default of goal io.fabric8:fabric8-maven-plugin:3.5.33:build failed: Cannot extract generator config: org.apache.maven.plugin.MojoExecutionException: Failed to add devtools files to fat jar C:\tmp\app-sample\target\app-sample-1.0-SNAPSHOT.jar. java.io.IOException: Failed to delete original file 'C:\tmp\app-sample\target\app-sample-1.0-SNAPSHOT.jar' after copy to 'C:\TEMP\user1\app-sample-1.0-SNAPSHOT.jar6705264538840591172.tmp'`

### CODE REVIEW

**Comment by hrishin** [comment]
@eye0fra Thanks a lot for this PR :)

fix for #1118

**Comment by rhuss** [comment]
Not merged ?

**Comment by hetzge** [comment]
I have tried fabric8:watch with different versions (3.5.42, 4.0.0-M2) and always get the error mentioned here.

**Comment by rohanKanojia** [comment]
@hetzge : Could you please share your sample project so that I can reproduce your issue?

**Comment by vineet-goel** [comment]
@rohanKanojia I have the same problem. I am using verison 4.0.0-M2
Attached is a simple springboot application.
[oclab.zip](https://github.com/fabric8io/fabric8-maven-plugin/files/2915194/oclab.zip)

Please let me know if you need more information to debug the issue. 

PS: I can see the PR is closed but not merged in master branch.

**Comment by vineet-goel** [comment]
@rohanKanojia  The previous attachement is missing a file _docker-compose.yml_. Therefore, you can skip the previous attachement and use the new one
[oclab.zip](https://github.com/fabric8io/fabric8-maven-plugin/files/2915233/oclab.zip)

**Comment by hetzge** [comment]
Here is also my sample project. It is a simple spring quick start with the fabric8 plugin.

I use:
Windows 10 Enterprise 
Version 1803
Betriebssystembuild 17134.590

I think it should be a generel problem if you test it with Windows.

This is the error i get:
`Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.42:watch (default-cli) on project demo: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.5.42:watch failed: Cannot extract generator config: org.apache.maven.plugin.MojoExecutionException: Failed to add devtools files to fat jar C:\Users\me\workspace\customer\demo\target\demo-0.0.1-SNAPSHOT.jar. java.io.IOException: Failed to delete original file 'C:\Users\me\workspace\customer\demo\target\demo-0.0.1-SNAPSHOT.jar' after copy to 'C:\Users\me\AppData\Local\Temp\demo-0.0.1-SNAPSHOT.jar17003983972646567801.tmp'
`

[demo.zip](https://github.com/fabric8io/fabric8-maven-plugin/files/2918548/demo.zip)

**Comment by vineet-goel** [comment]
@rohanKanojia Did you get time to look into it?

**Comment by rohanKanojia** [comment]
@vineet-goel : ah, no. Unfortunately, I couldn't find a windows machine to test this.

**Comment by rohanKanojia** [comment]
@vineet-goel : bdw, Would really appreciate if you could pull this pr onto your machine and test this fix on your machine(since you're on windows already). Let me re-open this .

**Comment by rohanKanojia** [comment]
@vineet-goel : Polite ping, did you get any chance to test this? Anyway, I don't see any harm in merging this since it's only trying with resources.

**Pull request merged**
