### PR TITLE
Spring Boot fixes: use server port from application.properties as default port and add scheme to probes

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks ! looks good to me.

Could you please add some words to the [spring generator docs](https://github.com/fabric8io/fabric8-maven-plugin/blob/3febbc7ea20a1a380a9bad2accfcfd09d00f94f3/doc/src/main/asciidoc/inc/generator/_spring_boot.adoc#L1-L1). _yes, for some parts we have docs ;-)_

**Comment by jimmidyson** [comment]
Added some docs - hope they're alright.

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
[merge]

**Comment by davsclaus** [comment]
@jimmidyson this is really nice work.

**Comment by jimmidyson** [comment]
Thanks for merging. Would love to get a release of this out so I can use these fixes in a demo of automatic TLS setup on openshift.

**Comment by rhuss** [comment]
I can do a release right now. @davsclaus is this ok for you ? Unfortunately I dont have time today for reviewing the other PRs but will pick them up at the end of next week (or earlier if this is urgent)

**Comment by davsclaus** [comment]
Yeah sure.

**Comment by rhuss** [comment]
@jimmidyson 3.2.8 is out ...

**Comment by jimmidyson** [comment]
Thanks!

**Pull request merged**
