### PR TITLE
clarify that adding the deploy goal to the f-m-p executions is only i…

### PR DESCRIPTION
**Pull request by christian-posta**
…f you'd like to deploy to kubernetes each time you run mvn install

### CODE REVIEW

**Comment by rhuss** [comment]
Actually you should *never* bind `deploy` to an execution as it forks the lifecycle so that you will end up in running goals twice. Instead use `apply` for this.

**Comment by christian-posta** [comment]
thanks @rhuss updated the PR

**Comment by davsclaus** [comment]
@rhuss lgtm. Should we get this merged?

**Comment by rhuss** [comment]
yeah

[merge]

**Pull request merged**
