### PR TITLE
bump version of kubernetes client...

### PR DESCRIPTION
**Pull request by nbyl**
to profit of more robust certificate parsing (e.g. https://github.com/fabric8io/kubernetes-client/pull/1021)

### CODE REVIEW

**Comment by piyush1594** [comment]
I think we should wait for 3.1.11 and will move to that. It has some changes which should be included/required in FMP

**Comment by piyush1594** [comment]
Issues should be resolved are #1236 #1221 #1159

**Comment by piyush1594** [comment]
issues on client https://github.com/fabric8io/kubernetes-client/issues/1013

**Comment by rohanKanojia** [comment]
Hm, If this change is not urgently required.. let's wait till we release kubernetes-client 3.1.11. When are we planning for our k8-client's next release?

**Comment by piyush1594** [comment]
We can upgrade the client in FMP NOW but I think the next release of FMP will be after this. As this issue will get fixed we can do a release in 2-3 weeks of client I think.

**Comment by nbyl** [comment]
@rohanKanojia We need this change pretty soon because we are encountering some certificate problems  which will be solved by  fabric8io/kubernetes-client#1021.The sooner the release comes, the better.

**Comment by piyush1594** [comment]
We can bump the client version to latest but the release of FMP is not scheduled right now for the time being.

**Comment by piyush1594** [comment]
As #1294 is raised, I am closing this

**Pull request closed without merging**
