### PR TITLE
dummy change to test PR build with Maven 3.5.2

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by piyush1594** [comment]
ok to test

**Comment by apupier** [comment]
it has not worked as i expected.
Maven version has been changed in the job config for jenkins but for Travis it is still using Maven 3.3.9 https://travis-ci.org/fabric8io/fabric8-maven-plugin/jobs/397348506#L1454
I don't know how to modify it, I found no reference in codebase to 3.3.9 and [one for 3.5.2](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/.mvn/wrapper/maven-wrapper.properties) (which seems not used in the build then?)

**Comment by rohanKanojia** [comment]
@apupier : Right now we don't specify maven version in these integration tests. I think it can be configured here using option `useMaven3Version`: https://github.com/fabric8io/fabric8-maven-plugin/blob/e7ea8bff53bb7f8035d27b0e587df0810d71b144/rt/src/test/java/io/fabric8/maven/rt/BaseBoosterIT.java#L204-L209

**Comment by apupier** [comment]
I'm closing this issue. it shows that the problem was not in fabric8-maven-plugin itself.
Based on that I was able to find that the issue is related to an incompatibility within the embedded Maven version in Eclipse and fabric8-maven-plugin. I think the issue is more on Eclipse side.
Thanks for your help!

**Pull request closed without merging**
