### PR TITLE
Removed OSIO enricher module

### LINKED ISSUE #1592: Remove unused/deprecated OSIO enrichers.
https://github.com/fabric8io/fabric8-maven-plugin/tree/master/enricher/osio

### PR DESCRIPTION
**Pull request by dev-gaur**
Fixes #1592

### CODE REVIEW

**Comment by dev-gaur** [comment]
This is strange. Build is passing on my local machine.

**Comment by dev-gaur** [comment]
CircleCI builds use cache. Probably that's the reason for build failure.

**Comment by rohanKanojia** [comment]
@dev-gaur : Could you please push again? So that CI can run again? Somehow I'm not able to re run the job

**Comment by dev-gaur** [comment]
> Looks good, Could you please remove documentation also for these enrichers?

Done.

> @dev-gaur : Could you please push again? So that CI can run again? Somehow I'm not able to re run the job

Yes I've tried this. Its the cache in CircleCI that's the cause for failure.
Can you please try building locally on your machine ?

**Comment by dev-gaur** [comment]
> Build is failing because you haven't removed references to `fabric8-maven-enricher-osio` from parent and plugin modules.

Done. Thanks for the help.

**Pull request merged**
