### PR TITLE
Fix #1714: mvn fabric8:resource converts types of kubernetes YAML annotations in fragment

### LINKED ISSUE #1714: mvn fabric8:resource converts types of kubernetes YAML annotations in fragment
### Info

* f-m-p version : 4.2.0
* Maven version (`mvn -v`) : 3.6.2
```
metadata:
  annotations:
    # Enable client certificate authentication
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'

```

After doing whatever it does to an ingress resource fragment (taken from the nginx ingress controller examples), the f-m-p will emit:

```
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: on

```

Note the lack of quotes. This results in the warning:

`[message=.metadata.annotations.nginx.ingress.kubernetes.io/auth-tls-verify-client: boolean found, string expected, violation type=type]`

The difference matters quite a bit as the wrong type will stop the ingress controller from actually enforcing client certificate auth...

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fixes #1714 

Modified Jackson ObjectMapper to disable minimizing quotes in case of yamls

### CODE REVIEW

**Comment by rohanKanojia** [comment]
tested on https://github.com/r0haaaan/fmp-sample-external-resources with and without this patch.

**Comment by erikgb** [comment]
@rohanKanojia : I can confirm that the PR actually fixes my conrete problem as reported in #1714. Well done and thanks!

**Comment by erikgb** [comment]
@rohanKanojia : I am checking out the latest version, with this fix (4.3.0). The fix seems to have made the generated resources less readable, specifically when creating ConfigMap resources from file.

Given:
````yaml
metadata:
  annotations:
    maven.fabric8.io/cm/declarative.yaml: kong-config.yaml
````
````yaml
_format_version: "1.1"

services:
- name: my-service
  url: https://example.com
  plugins:
  - name: key-auth
  routes:
  - name: my-route
    paths:
    - /

consumers:
- username: my-user
  keyauth_credentials:
  - key: my-key

````

f-m-p 4.3.0:
````yaml
data:
  declarative.yaml: "_format_version: \"1.1\"\n\nservices:\n- name: my-service\n \
    \ url: https://example.com\n  plugins:\n  - name: key-auth\n  routes:\n  - name:\
    \ my-route\n    paths:\n    - /\n\nconsumers:\n- username: my-user\n  keyauth_credentials:\n\
    \  - key: my-key\n"

````
f-m-p 4.2.0:
````yaml
data:
  declarative.yaml: |
    _format_version: "1.1"

    services:
    - name: my-service
      url: https://example.com
      plugins:
      - name: key-auth
      routes:
      - name: my-route
        paths:
        - /

    consumers:
    - username: my-user
      keyauth_credentials:
      - key: my-key
````

It looks ok again in the cluster console, but I must admit that I would have preferred to have the generated resource more readable.
What do you think? Is there a (quick) fix?

**Comment by rohanKanojia** [comment]
@erikgb : Not sure. Actually we were minimising quote in jackson while converting to yaml. For your env fix, I had to disable that:
https://github.com/fabric8io/fabric8-maven-plugin/blob/fa070a9fe6b6c4939ba7fc6e697429917821e19b/core/src/main/java/io/fabric8/maven/core/util/ResourceUtil.java#L90-L100

**Comment by erikgb** [comment]
@rohanKanojia : Ok, I can live it. At least for now - lesser evil. ;-) I can try to dig in to the Jackson settings and experiment a bit....

**Comment by rohanKanojia** [comment]
I also noticed that yamls are less readable with this, but I thought maybe we need to compromise over readability for fixing that bug. But it would be awesome if we can find some way to have both readability and selective quote addition(not sure about this though!)

**Comment by rohanKanojia** [comment]
@erikgb : Anyway, I'm done for the week. I would try to look into this next week. Have a nice weekend!

**Comment by erikgb** [comment]
@rohanKanojia : Same to you! Have a nive weekend!

**Pull request merged**
