### PR TITLE
upgraded docker-maven-plugin version to latest along with adding .gitignore

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by jstrachan** [comment]
ok to test

**Comment by rhuss** [comment]
ok to test

**Comment by rhuss** [comment]
retest this please

**Comment by rhuss** [comment]
retest this please

**Comment by rhuss** [comment]
retest this please

**Comment by rhuss** [comment]
retest this please

**Comment by rhuss** [comment]
retest this please

**Comment by rhuss** [comment]
retest this please

**Comment by rhuss** [comment]
retest this please

**Comment by rhuss** [comment]
Manually merging this time (because of missing snapshot repository it won't work)

**Pull request merged**
