### PR TITLE
fix logic of extracting sha from imagestream

### PR DESCRIPTION
**Pull request by pwielgolaski**
addressing https://github.com/fabric8io/fabric8-maven-plugin/issues/1189

I'm not sure if old assumption was valid 

> // latest item is the first
but based on response from openshift.io it is opposite

### CODE REVIEW

**Comment by pwielgolaski** [comment]
it seems that after 1.0.9 version 1.0.10 will not be last.

```
{
    "kind": "ImageStreamList",
    "apiVersion": "v1",
    "metadata": {
        "selfLink": "/oapi/v1/namespaces/pwielgolaski-jenkins/imagestreams",
        "resourceVersion": "943866445"
    },
    "items": [
        {
            "metadata": {
                "name": "portal",
                "namespace": "pwielgolaski-jenkins",
                "selfLink": "/oapi/v1/namespaces/pwielgolaski-jenkins/imagestreams/portal",
                "uid": "81ea0857-10d1-11e8-af4a-02e52a0be43d",
                "resourceVersion": "940862537",
                "generation": 1,
                "creationTimestamp": "2018-02-13T15:21:04Z",
                "labels": {
                    "app": "portal",
                    "group": "luxtorpeda",
                    "provider": "fabric8",
                    "version": "1.0.1"
                }
            },
            "spec": {
                "lookupPolicy": {
                    "local": false
                }
            },
            "status": {
                "dockerImageRepository": "172.30.98.11:5000/pwielgolaski-jenkins/portal",
                "tags": [
                    {
                        "tag": "1.0.1",
                        "items": [
                            {
                                "created": "2018-02-13T16:41:54Z",
                                "dockerImageReference": "172.30.98.11:5000/pwielgolaski-jenkins/portal@sha256:d4f1b2873b3038a60e431c57faf0369280dd69d41134d1f9e045f88631ffd394",
                                "image": "sha256:d4f1b2873b3038a60e431c57faf0369280dd69d41134d1f9e045f88631ffd394",
                                "generation": 1
                            },
                            {
                                "created": "2018-02-13T15:21:59Z",
                                "dockerImageReference": "172.30.98.11:5000/pwielgolaski-jenkins/portal@sha256:ef886805de42294bac0762dba71c83c6d5a63f7bb31693e4fe858ff93fc16b53",
                                "image": "sha256:ef886805de42294bac0762dba71c83c6d5a63f7bb31693e4fe858ff93fc16b53",
                                "generation": 1
                            }
                        ]
                    },
                    {
                        "tag": "1.0.10",
                        "items": [
                            {
                                "created": "2018-02-14T17:32:29Z",
                                "dockerImageReference": "172.30.98.11:5000/pwielgolaski-jenkins/portal@sha256:e71d4b041b4dac9ffcb89d8d0b704662b81f367210e20c392ee0b87699a90a0e",
                                "image": "sha256:e71d4b041b4dac9ffcb89d8d0b704662b81f367210e20c392ee0b87699a90a0e",
                                "generation": 1
                            }
                        ]
                    },
                    {
                        "tag": "1.0.11",
                        "items": [
                            {
                                "created": "2018-02-14T20:15:14Z",
                                "dockerImageReference": "172.30.98.11:5000/pwielgolaski-jenkins/portal@sha256:22e63f6a0065406f46111112adc13c79be129ddc2779ad25690ff9e4564dfea9",
                                "image": "sha256:22e63f6a0065406f46111112adc13c79be129ddc2779ad25690ff9e4564dfea9",
                                "generation": 1
                            }
                        ]
                    },
                    {
                        "tag": "1.0.12",
                        "items": [
                            {
                                "created": "2018-02-14T20:49:12Z",
                                "dockerImageReference": "172.30.98.11:5000/pwielgolaski-jenkins/portal@sha256:aaab5df193e1bad9a2f4fd1583f18ce6b265ca27636352ef995ac38837897c3c",
                                "image": "sha256:aaab5df193e1bad9a2f4fd1583f18ce6b265ca27636352ef995ac38837897c3c",
                                "generation": 1
                            }
                        ]
                    },
                    {
                        "tag": "1.0.2",
                        "items": [
                            {
                                "created": "2018-02-13T17:41:15Z",
                                "dockerImageReference": "172.30.98.11:5000/pwielgolaski-jenkins/portal@sha256:d3504941bcf33c9a970b362ba2fb0da3ce099f320a379808618d75612e0ecb64",
                                "image": "sha256:d3504941bcf33c9a970b362ba2fb0da3ce099f320a379808618d75612e0ecb64",
                                "generation": 1
                            }
                        ]
                    },
                    {
                        "tag": "1.0.3",
                        "items": [
                            {
                                "created": "2018-02-13T18:18:51Z",
                                "dockerImageReference": "172.30.98.11:5000/pwielgolaski-jenkins/portal@sha256:a076939194a4d8c7951ff5ecae93f22779532c44741fc5785d2725b9223fcc7b",
                                "image": "sha256:a076939194a4d8c7951ff5ecae93f22779532c44741fc5785d2725b9223fcc7b",
                                "generation": 1
                            }
                        ]
                    },
                    {
                        "tag": "1.0.4",
                        "items": [
                            {
                                "created": "2018-02-13T18:55:11Z",
                                "dockerImageReference": "172.30.98.11:5000/pwielgolaski-jenkins/portal@sha256:362891f04331cab1b0f7e54801dc9c1091ba669140dec80c504a5f4e794b11bd",
                                "image": "sha256:362891f04331cab1b0f7e54801dc9c1091ba669140dec80c504a5f4e794b11bd",
                                "generation": 1
                            }
                        ]
                    }
                ]
            }
        }
    ]
}
```

**Comment by pwielgolaski** [comment]
maybe we should filter only specific tag in https://github.com/pwielgolaski/fabric8-maven-plugin/blob/f8f479e33cf751677fa7784bea4570cf3f4d3b7b/core/src/main/java/io/fabric8/maven/core/service/openshift/ImageStreamService.java#L204

now when we have more than one, first SHA is taken

**Comment by piyush1594** [comment]
@pwielgolaski  Would you like to rebase and push again.

**Comment by hrishin** [comment]
It has been fixed

**Comment by piyush1594** [comment]
fixed in https://github.com/fabric8io/fabric8-maven-plugin/pull/1225

**Pull request closed without merging**
