### PR TITLE
Wait timeout for build pod is too small

### PR DESCRIPTION
**Pull request by bohmber**
Signed-off-by: bohmber <bommel@apache.org>

### CODE REVIEW

**Comment by bohmber** [comment]
60 sec is not enough in some cases

**Comment by bohmber** [comment]
@dev-gaur you can do the squash it during merge?

**Comment by bohmber** [comment]
This is the error if the build pod is not ready:
`[INFO] F8: Waiting for build xxxx-yyyy-zzzz-46 to complete...`
`[INFO] F8: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"docker-build\" in pod \"xxxx-yyyy-zzzz-46-build\" is waiting to start: PodInitializing","reason":"BadRequest","code":400}`

**Comment by bohmber** [comment]
@rohanKanojia changelog added

**Comment by rohanKanojia** [comment]
@bohmber : Thanks, looks good :+1: .Just waiting for Alex's approval ;-)

**Pull request merged**
