### PR TITLE
OSFUSE-473: Allows using build goal without using resource goal

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
@jimmidyson do we need goal tests now to hit changed code and pass codecov?

**Comment by jimmidyson** [comment]
@dhirajsb Probably a question for @rhuss as the core maintainer of this plugin rather than me. I'm sure it would be good to have _some_ coverage of changes though.

**Comment by dhirajsb** [comment]
@rhuss since the PR is for running build goal, it's kinda hard to integration test it, since it will need a k8s environment, and the generated imagestream manifest with sha256 tag is not fixed.

**Comment by rhuss** [comment]
Actually this PR is associated with #768 , and the actual question is, whether the generation of these imagestreams tags are required at all. The arguments to remove this are given in the issue above, so I really would like to find another solution to create these sort of tags and avoid a coupling of 'fabric8:resource' with 'fabric8:build' indirectly via the resource descriptors so that they can be used independently. Its not good that the OpenShift state is different whether `mvn clean fabric8:resource fabric8:build` is different when then for `mvn clean fabric8:build`. So simply ignoring when no resources are there is not a solution.

w.r.t to the code coverage: @dhirajsb I see you point that Mojos are hard to test and a lot would have been to be mocked. Since this Mojos tend to grow to monsters, the solution is to refactor stuff into Maven independent objects (like the 'ServiceHub'), so that the Mojos are only a thin layer over the business logic, not containing the logic.

said that, for such a small change, I wouldn't mind to merge nevertheless. Its not the missing test, why I hesitate to include it, but because of the arguments given above.

**Comment by rhuss** [comment]
This PR is superseded by #782

**Pull request closed without merging**
