### PR TITLE
Fixed executable lookup on non windows systems

### PR DESCRIPTION
**Pull request by SlavoKrupa**
In current master the lookup of executables was performed only on windows system

### CODE REVIEW

**Comment by jstrachan** [comment]
@SlavoKrupa many thanks!

**Comment by jstrachan** [comment]
lgtm [merge]

**Comment by jstrachan** [comment]
ok to test

**Comment by rhuss** [comment]
@jstrach @chirino submitted a similar patch yesterday which I have applied

**Comment by rhuss** [comment]
@jstrachan see last comment

**Comment by jstrachan** [comment]
ah ok thanks! lemme close this one for now then

**Pull request closed without merging**
