### PR TITLE
Fix 1247: do not try to install non-existent imagestream yml file

### PR DESCRIPTION
**Pull request by nicolaferraro**
With this change the plugin will not try to install into maven repository the yml imagstream if not generated.
#1247

### CODE REVIEW

**Comment by hrishin** [comment]
LGTM

cc: @rohanKanojia @piyush1594

**Comment by nicolaferraro** [comment]
Apart from the issue, I find it useful every time I want the plugin to just deploy some resources from `src/main/fabric8` without building a container image.

I think tests are stuck for other reasons..

**Comment by piyush1594** [comment]
Yaa some issues with test @nicolaferraro , Fixing it here #1253

**Comment by nicolaferraro** [comment]
[merge]

**Pull request merged**
