### PR TITLE
fixes #167

### LINKED ISSUE #167: migrating some projects in fabric8-devops to the new plugin breaks
as there's no longer a JSON OpenShift Template available

so for now lets by default generate yml and json files as a workaround

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by jstrachan** [comment]
[merge]

**Comment by jstrachan** [comment]
LGTM

**Comment by jimmidyson** [comment]
Are you happy for us to revert this once we migrate stuff over to the new plugin? No need for both JSON & YAML in the end is there?

**Comment by jstrachan** [comment]
Absolutely - was just a tactical workaround to try get fabric8-devops releaseable

**Pull request merged**
