### PR TITLE
. #333 - Initial implementation for using `gofabric8 docker-env` as a fallback.

### PR DESCRIPTION
**Pull request by rhuss**
* Not yet done: Call of 'fabric8:install' in case there is now gofabric8 in the path. Currently the goal bails out.
* Requires 0.15-SNAPSHOT of d-m-p
* Also still open: `gofabric8 docker-env` asks for user + password if not connected, but this shouldnt be the case (an empty string should be printed). See  https://github.com/fabric8io/gofabric8/issues/175 for this issue.

### CODE REVIEW

**Comment by rhuss** [comment]
lgtm [merge]

**Comment by rhuss** [comment]
lgtm

**Comment by jstrachan** [comment]
@rhuss would love a release once the snapshot of d-m-p is removed!

**Comment by rhuss** [comment]
@jstrachan will do it today

**Pull request merged**
