### PR TITLE
Bump version to 4.0-SNAPSHOT

### LINKED ISSUE #1065: Release new 4.0.0 of fabric8-maven-plugin?
we've just cut the new major version of the kubernetes-model (2.x), kubernetes-client (3.x) and fabric8 (3.x) to include the latest kubernetes 1.7 schema stuff inside.

it'd be nice to get a version of fabric8-maven-plugin out using the new schema (once it works ;).

Should we bump to a major new version for fabric8-maven-plugin to indicate the new schema version?

### PR DESCRIPTION
**Pull request by nicolaferraro**
Let's prepare for next release.

Fixes #1065

### CODE REVIEW

**Comment by hrishin** [comment]
Nice @nicolaferraro 
I think we must update the CHANGELOG.md, at least to mention compatibility of it with Kubernetes/OpenShift?

**Comment by nicolaferraro** [comment]
Thanks @hrishin , we should try to enforce writing to changelog for any PR..

**Comment by nicolaferraro** [comment]
@hrishin have you tested the plugin with 1.7/3.7 or 1.5/3.5?

**Comment by hrishin** [comment]
> Thanks @hrishin , we should try to enforce writing to changelog for any PR..

Totally agreed!

> @hrishin have you tested the plugin with 1.7/3.7 or 1.5/3.5?

Some testing with OS 3.7 using the resource, deploy, debug goals. Thing works but something is not looking right with either with F8-M-P or OS 3.7

Deploy:
Logs
```
[INFO] F8: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"sti-build\" in pod \"fabric8-maven-sample-spring-boot-s2i-2-build\" is waiting to start: PodInitializing","reason":"BadRequest","code":400}
[INFO] Current reconnect backoff is 1000 milliseconds (T0)
[INFO] Current reconnect backoff is 2000 milliseconds (T1)
[INFO] Current reconnect backoff is 4000 milliseconds (T2)
[INFO] F8: Build fabric8-maven-sample-spring-boot-s2i-2 Complete
[INFO] Current reconnect backoff is 8000 milliseconds (T3)
```
Debug:
Getting `Image Pull Back-off` status for pod

**Comment by nicolaferraro** [comment]
No compatibility with origin 1.5 from my tests (this may justify version bump), for the resource version problem.

**Comment by nicolaferraro** [comment]
@hrishin if this passes, do you mind merging it so we release 4.0 as next version?

**Comment by hrishin** [comment]
@nicolaferraro sure we can :+1: @kameshsampath @pradeepto ?
If we want to release it as 4.0 then its time to include version support matrix between the plugin and Kubernetes/OpenShift in README.md and docs as well.

**Comment by kameshsampath** [comment]
@nicolaferraro  and @hrishin  - remember we spoke to have 4.0 as next major release with refactoring wondering if we should so 3.x maintenance releases as part of it ?

CC: @pradeepto

**Comment by nicolaferraro** [comment]
We can bump the version to 4.0 consistently with what done by kubernetes-model and kubernetes-client, since we are now using the new major version of them on master.
We can create a 3.x maintenance branch when needed.

**Comment by hrishin** [comment]
@nicolaferraro @kameshsampath what key things we consider for a major release in f8-m-p context?

**Comment by mojsha** [comment]
@hrishin I am also getting those errors in OpenShift 3.7. 

On a general note: It looks like the work on the F-M-P has slowed down; is it  because people are busy working on 4.0 or have key contributors pulled out of the project (such as @ro14nd)?

**Comment by nicolaferraro** [comment]
@mojsha most of the errors for Openshift 3.7 should have been solved now (do we need to release @hrishin ?). Can you explain better what you are getting?

**Comment by mojsha** [comment]
It's basically the one described here https://github.com/fabric8io/fabric8-maven-plugin/issues/1159 although in some cases the build / deploy fails or takes very long. 

Second thing  - unrelated to 3.7 - is that 3.5.34 is not yet released (it solved dependencies on external json schemas) although there is a tag in the code repository. I would think @hrishin should release it, even though 4.0.0 is underway.

**Pull request closed without merging**
