### PR TITLE
Update pom property version.fabric8 to 2.2.184

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
[merge] lgtm

**Comment by davsclaus** [comment]
There is a NPE in an unit test now
```
enrichSimple(io.fabric8.maven.plugin.enricher.EnricherManagerTest)  Time elapsed: 0.577 sec  <<< ERROR!
java.lang.NullPointerException
	at io.fabric8.maven.plugin.enricher.EnricherManagerTest.enrichSimple(EnricherManagerTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by davsclaus** [comment]
ok to test

**Comment by rhuss** [comment]
I'll take that

**Comment by rhuss** [comment]
Its a regression in the kubernetes-client. @iocanel is about to fix it. guess we will need a next release.

Good that we have that much unit tests (which in this case was provided by a contributor). 😜

**Comment by rawlingsj** [comment]
excellent!  and it was the CD pipeline that triggered the pull request of the new kubernetes-client version.  

fast feedback FTW :)

**Comment by rhuss** [comment]
I close this PR as we have to wait for the next release of fabric8

**Pull request closed without merging**
