### PR TITLE
switch from alpine to centos images #878

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by rhuss** [comment]
Sounds good to me. Maybe we should combine this in a new 3.3.0 release together with #877 (as I consider this to be a major change) ?

**Comment by jstrachan** [comment]
@rhuss sounds good to me

**Comment by rhuss** [comment]
@jstrachan jus tto be sure that the size implications are know: alpine == 99 MB, centos == 483 MB. Of course its cache but need to be reloaded for each new installation (minishift, etc.) We all know the discussion about size etc., don't want to waste any energy here now.

just wondering whether there are any other opinions on a default base image switch for non-s2i builds // @fabric8io/fabric8-admin

**Comment by jstrachan** [comment]
Yeah. The s2i images are based on jboss images which are centos based too. When folks start using other things like jenkins or whatever those are increasingly centos based as well; so am not sure folks are gonna be able to do much on minikube/minishift without downloading a base centos image am afraid.

Its a shame we can't make things tiny OOTB; but having things work (DNS is kinda handy!) seems more important than caching a centos base layer unfortunately. (Would love it if minikube/minishift could reuse the cached docker layers between VMs to speed things up ;)

**Comment by rhuss** [comment]
If we want to align with the s2i bits, maybe its better to switch to `fabric8/java-jboss-openjdk8-jdk` which uses the same base image `jboss/base-jdk:8` as the s2i image ?

**Comment by jstrachan** [comment]
@rhuss sounds good to me

**Comment by rhuss** [comment]
ok, just pushed an update.

**Comment by rhuss** [comment]
looks good to me

[merge]

**Pull request merged**
