### PR TITLE
OSFUSE-47 - general Karaf readiness probe for Karaf template and quic…

### PR DESCRIPTION
**Pull request by chirino**
…kstarts.

Lets discover if the karaf deployment has health checks enabled and add them to the k8s config.

### CODE REVIEW

**Comment by rawlingsj** [comment]
add to whitelist

**Comment by chirino** [comment]
test this please

**Comment by chirino** [comment]
lgtm

**Comment by chirino** [comment]
lgtm [merge]

**Comment by rawlingsj** [comment]
[merge]

**Comment by rawlingsj** [comment]
lgtm [merge]

**Pull request merged**
