### PR TITLE
Upgrade Jgit to version 5.0.2.201807311906-r

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
cc @rhuss @nicolaferraro @piyush1594 @hrishin

**Comment by oscerd** [comment]
forgot @rohanKanojia :-)

**Comment by rohanKanojia** [comment]
:smile:

**Comment by nicolaferraro** [comment]
[merge]

**Comment by rhuss** [comment]
If its targeted to 3.5, too, don't forget to cherry pick on the 3.5.x branch, too. We have branched off yestereday right after the release.

**Pull request merged**
