### PR TITLE
Add license maven plugin for better license management in fmp

### PR DESCRIPTION
**Pull request by rohanKanojia**

### CODE REVIEW

**Comment by samolisov** [comment]
Amazing job! I've used the PR to add the headers to my Java EE 8 example in #1152. One question: why is year 2016 included in the copyright?

**Comment by rohanKanojia** [comment]
@samolisov : Because this project was started in 2016, that's why.

**Comment by rohanKanojia** [comment]
@hrishin @rhuss @nicolaferraro : Does this look like a sane change to you guys? Otherwise shall I close this PR?

**Comment by nicolaferraro** [comment]
@rohanKanojia I think it's ok to merge it (before you get too many conflicts) :)

**Comment by rohanKanojia** [comment]
I'm going to update this soon

**Comment by rhuss** [comment]
Ok, lets get that merge before it gets stale again.

@rohanKanojia do you think we need something similar for the 3.5 branch ?

**Comment by rhuss** [comment]
yeah, fine with this. Didn't want to generate artificial work :)

**Pull request merged**
