### PR TITLE
#665: Remove break from service port iteration

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by rhuss** [comment]
retest please

**Comment by rhuss** [comment]
test this please

**Comment by jimmidyson** [comment]
Think this will also add the Prometheus & jolokia ports to the service for Java exec generators won't it? We don't want that. I think single port is good enough for now with yaml files providing extra ports as required.

**Comment by davsclaus** [comment]
Good observations @jimmidyson - I think a single service is the norm over http. 

So if people want additional I am fine with them having to explicit configure this somewhere.

**Comment by rhuss** [comment]
But which one should be taken when there are multiple ports exposed ? Arbitrarly the first one exposed in the Docker image ? If so, that must be well documented.

**Comment by jimmidyson** [comment]
Choices:

* Require port to always be explicitly specified (not a great UX IMO)
* Only add the service port if there is a single port exposed, otherwise require explicit configuration (all of our Javaimages expose multiple ports IIRC so won't apply to much of our stuff & we are the largest consumer of course).
* Add first port discovered & document that behaviour. I think this works for about ~90% of use cases but could of course be wrong about that.

**Comment by rhuss** [comment]
For me its fine to take the first one. The service enricher could even let this behaviour be configurable, e.g. adding a 'mode' with values 'first' or 'all' (just as example. could be also a 'ports' which takes a numeric list, or these two literal string values)

**Comment by jimmidyson** [comment]
Either way, I think this PR should be closed & more discussion in #665 to come up with the right way to handle it.

**Comment by rhuss** [comment]
Added an alternate suggestion to #665 , so going to close this PR for now.

**Pull request closed without merging**
