### PR TITLE
#1113-test env setup : Make OpenShift cluster up & running 

### PR DESCRIPTION
**Pull request by hrishin**
**Enable test environment to run regression tests**
This is the change in travis configuration to run the regression test for fabric8 starter projects. We are choosing travis for testing it because existing fabric8 pipelines have limitations to run the test.

**Changes**
 - download and install `kubectl`, `oc` CLI client tools
 - configure docker daemon to run insecure registry for OpenShift cluster
 - execute `oc cluster up` with different metrics profile
 - added maven wrapper

### CODE REVIEW

**Comment by rawlingsj** [comment]
add to whiltelist

**Comment by hrishin** [comment]
ok to test

**Comment by rawlingsj** [comment]
add to whitelist

**Comment by hrishin** [comment]
@kameshsampath @rhuss @nicolaferraro 
Is it good to go?

**Comment by nicolaferraro** [comment]
looks great @hrishin. Are there tests configured to run currently? (Haven't seen them in the travis log)

**Comment by hrishin** [comment]
Thank you @nicolaferraro not yet, it will be the prerequisite to run it regression tests.

**Pull request merged**
