### PR TITLE
fix aggregation on OpenShift

### LINKED ISSUE #1607: aggregating YAMLs doesn't work for OpenShift with FMP 4.0.0
### Description

The `fmp-dependency` enricher (`DependencyEnricher` class) can aggregate multiple YAMLs available on classpath. In FMP version 4.0.0, this doesn't work for OpenShift -- the aggregated files are identical to the Kubernetes YAMLs.

It's probably easiest for me to explain it on an example. Steps to reproduce:

1. git clone -b update-to-2.4.0 https://github.com/Ladicek/thorntail-circuit-breaker.git
1. cd thorntail-circuit-breaker
1. mvn clean verify -Popenshift,openshift-it
1. observe error `Could not resolve route: thorntail-circuit-breaker-name. Available routes: []`

At this point, look into `tests/target/classes/META-INF/fabric8/`. The `kubernetes` directory and `kubernetes.yml` file are OK, exactly what I'd expect. However, the `openshift` directory and `openshift.yml` file are identical to `kubernetes` / `kubernetes.yml`, which is definitely _not_ what I expect. I expect the aggregate to be, well, an aggregate of the OpenShift files from the `name-service` and `greeting-service` modules.

This works fine in 4.0.0-M2. I was able to track the issue down to this change: https://github.com/fabric8io/fabric8-maven-plugin/commit/9b648cfaf76a04517ff0a6895170019b6006d428#diff-c7c605106d3e8005f2161d83dce35592

### Info

* f-m-p version : 4.0.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /home/lthon/software/apache-maven
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-oracle/jre
Default locale: cs_CZ, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-46-generic", arch: "amd64", family: "unix"
```
* Kubernetes / OpenShift setup and version : OKD 3.11 with Minishift 1.32
* If it's a bug, how to reproduce : see above
* Sample project : https://github.com/Ladicek/thorntail-circuit-breaker.git # note that the `update-to-2.4.0` branch is required

### PR DESCRIPTION
**Pull request by Ladicek**
Resolves #1607

### CODE REVIEW

**Comment by Ladicek** [comment]
I will elaborate more next week, it's Friday afternoon :-)

**Comment by Ladicek** [comment]
I filed #1607 with more details. I'd like to understand if this fix is good (it does work for me :-) ), and also when could this be available in a release. It's blocking us, the Thorntail team, to fully upgrade to FMP 4.0.0.

**Comment by Ladicek** [comment]
Rebased.

**Comment by Ladicek** [comment]
Bump?

**Comment by rohanKanojia** [comment]
@Ladicek : Thanks, will look into your PR soon

**Comment by Ladicek** [comment]
Done, thanks!

**Pull request merged**
