### PR TITLE
fixed unizp issue

### PR DESCRIPTION
**Pull request by hrishin**
- droped unsed method that coulod cause CEV issue

### CODE REVIEW

**Comment by piyush1594** [comment]
@rohanKanojia you need to wait for CI to pass so that we are confident enough.

**Comment by rohanKanojia** [comment]
@piyush1594 : This PR is just removing an unused function. I fail to see how can we lose confidence from this.

**Comment by piyush1594** [comment]
I agree that we are removing an unused function but I think we should wait for it. That's the purpose we worked on that.

**Comment by piyush1594** [comment]
It's not about losing confidence. It's about proving in the better way.

**Comment by rohanKanojia** [comment]
Not sure what you mean. I thought the change was trivial enough to be merged. Sorry if I broke standard process. Will take care from next time.

**Comment by hrishin** [comment]
Thanks, @rohanKanojia! Let's adore the process.

**Pull request merged**
