### PR TITLE
OSFUSE-452: Added support for specifying pod name for log goal

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
[merge] lgtm

**Comment by davsclaus** [comment]
Its a bit weird but this has been merged

**Comment by davsclaus** [comment]
Ah its another branch, darn you RH ;)

**Comment by davsclaus** [comment]
[merge]

**Comment by dhirajsb** [comment]
Thanks @davsclaus

**Pull request merged**
