### PR TITLE
Remove default service type

### LINKED ISSUE #693: Change default service type from LoadBalancer to ClusterIP
### Description

Using `LoadBalancer` as standard type is not suitable in situation when there is no load balancer available. I guess the only save default is to use `ClusterIP` or nothing (which actually maps to `ClusterIP`, too). This lead also to issue within OpenShift (https://issues.jboss.org/browse/OSFUSE-469)

If an fabric8 environment we still can use the `exposecontroller` to change this type on the fly.

If there are not objection, I would remove the default (so that no type is added).

### PR DESCRIPTION
**Pull request by jimmidyson**
This is of course a breaking change - I think it's the right thing to do though.

Fixes #693

### CODE REVIEW

**Comment by davsclaus** [comment]
lgtm

I just deployed swarm-camel and it was using LoadBalancer and in my local minikube there is no such a thing and it was in pending state.

**Comment by davsclaus** [comment]
Maybe we can release the fmp as 3.3.0 then with this change in mind?

**Comment by jimmidyson** [comment]
Agreed. Can we merge this now?

**Comment by davsclaus** [comment]
@rhuss are you okay with this change and maybe release the next fmp as 3.3.0?

And @rawlingsj @jstrachan any thoughts?

**Comment by rhuss** [comment]
I'm fine with this

**Comment by jimmidyson** [comment]
Let's merge this -can always revert if needed.

**Pull request merged**
